import { ClothingItem } from '../types';
import { v4 as uuidv4 } from 'uuid';
import { subDays, subMonths } from 'date-fns';

const now = new Date();

export const sampleItems: Omit<ClothingItem, 'id' | 'createdAt'>[] = [
  {
    name: 'Classic White Button-Down',
    category: 'tops',
    color: 'white',
    brand: 'Everlane',
    size: 'M',
    purchasePrice: 78,
    imageUrl: 'https://images.unsplash.com/photo-1598032895397-b9472444bf93?w=400',
    seasons: ['spring', 'summer', 'fall'],
    occasions: ['work', 'casual', 'date'],
    favorite: true,
    wearCount: 24,
    lastWorn: subDays(now, 3).toISOString(),
    condition: 'good',
    estimatedValue: 40,
  },
  {
    name: 'Navy Blazer',
    category: 'outerwear',
    color: 'navy',
    brand: 'J.Crew',
    size: 'M',
    purchasePrice: 198,
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400',
    seasons: ['fall', 'winter', 'spring'],
    occasions: ['work', 'formal'],
    favorite: true,
    wearCount: 18,
    lastWorn: subDays(now, 7).toISOString(),
    condition: 'excellent',
    estimatedValue: 90,
  },
  {
    name: 'Black Skinny Jeans',
    category: 'bottoms',
    color: 'black',
    brand: 'AG Jeans',
    size: '28',
    purchasePrice: 178,
    imageUrl: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400',
    seasons: ['all'],
    occasions: ['casual', 'work', 'date', 'evening'],
    favorite: true,
    wearCount: 45,
    lastWorn: subDays(now, 1).toISOString(),
    condition: 'good',
    estimatedValue: 50,
  },
  {
    name: 'Floral Summer Dress',
    category: 'dresses',
    color: 'multicolor',
    brand: 'Reformation',
    size: 'S',
    purchasePrice: 218,
    imageUrl: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400',
    seasons: ['spring', 'summer'],
    occasions: ['casual', 'date', 'vacation'],
    favorite: false,
    wearCount: 3,
    lastWorn: subMonths(now, 4).toISOString(),
    condition: 'excellent',
    estimatedValue: 120,
  },
  {
    name: 'White Sneakers',
    category: 'shoes',
    color: 'white',
    brand: 'Common Projects',
    size: '9',
    purchasePrice: 425,
    imageUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400',
    seasons: ['spring', 'summer', 'fall'],
    occasions: ['casual', 'vacation'],
    favorite: true,
    wearCount: 67,
    lastWorn: subDays(now, 2).toISOString(),
    condition: 'fair',
    estimatedValue: 80,
  },
  {
    name: 'Cashmere Sweater',
    category: 'tops',
    color: 'gray',
    brand: 'Naadam',
    size: 'M',
    purchasePrice: 165,
    imageUrl: 'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=400',
    seasons: ['fall', 'winter'],
    occasions: ['casual', 'work'],
    favorite: true,
    wearCount: 12,
    lastWorn: subDays(now, 14).toISOString(),
    condition: 'excellent',
    estimatedValue: 100,
  },
  {
    name: 'Tailored Trousers',
    category: 'bottoms',
    color: 'beige',
    brand: 'Theory',
    size: '6',
    purchasePrice: 285,
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400',
    seasons: ['spring', 'summer', 'fall'],
    occasions: ['work', 'formal'],
    favorite: false,
    wearCount: 8,
    lastWorn: subMonths(now, 2).toISOString(),
    condition: 'excellent',
    estimatedValue: 140,
  },
  {
    name: 'Leather Ankle Boots',
    category: 'shoes',
    color: 'brown',
    brand: 'Frye',
    size: '8.5',
    purchasePrice: 328,
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400',
    seasons: ['fall', 'winter'],
    occasions: ['casual', 'work', 'date'],
    favorite: true,
    wearCount: 23,
    lastWorn: subDays(now, 5).toISOString(),
    condition: 'good',
    estimatedValue: 120,
  },
  {
    name: 'Silk Blouse',
    category: 'tops',
    color: 'pink',
    brand: 'Equipment',
    size: 'S',
    purchasePrice: 248,
    imageUrl: 'https://images.unsplash.com/photo-1551489186-cf8726f514f8?w=400',
    seasons: ['spring', 'summer', 'fall'],
    occasions: ['work', 'date', 'evening'],
    favorite: false,
    wearCount: 0,
    condition: 'excellent',
    estimatedValue: 150,
    notes: 'Still has tags',
  },
  {
    name: 'Denim Jacket',
    category: 'outerwear',
    color: 'blue',
    brand: "Levi's",
    size: 'M',
    purchasePrice: 98,
    imageUrl: 'https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=400',
    seasons: ['spring', 'fall'],
    occasions: ['casual', 'vacation'],
    favorite: true,
    wearCount: 31,
    lastWorn: subDays(now, 4).toISOString(),
    condition: 'good',
    estimatedValue: 45,
  },
  {
    name: 'Little Black Dress',
    category: 'dresses',
    color: 'black',
    brand: 'Diane von Furstenberg',
    size: '4',
    purchasePrice: 398,
    imageUrl: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400',
    seasons: ['all'],
    occasions: ['formal', 'evening', 'date'],
    favorite: true,
    wearCount: 6,
    lastWorn: subMonths(now, 1).toISOString(),
    condition: 'excellent',
    estimatedValue: 200,
  },
  {
    name: 'Running Shoes',
    category: 'shoes',
    color: 'gray',
    brand: 'Nike',
    size: '9',
    purchasePrice: 160,
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
    seasons: ['all'],
    occasions: ['athletic'],
    favorite: false,
    wearCount: 52,
    lastWorn: subDays(now, 1).toISOString(),
    condition: 'fair',
    estimatedValue: 30,
  },
  {
    name: 'Puffer Vest',
    category: 'outerwear',
    color: 'navy',
    brand: 'Patagonia',
    size: 'M',
    purchasePrice: 179,
    imageUrl: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400',
    seasons: ['fall', 'winter'],
    occasions: ['casual', 'athletic'],
    favorite: false,
    wearCount: 0,
    condition: 'excellent',
    estimatedValue: 120,
    notes: 'Gift - not my style',
  },
  {
    name: 'Striped T-Shirt',
    category: 'tops',
    color: 'navy',
    brand: 'Uniqlo',
    size: 'M',
    purchasePrice: 25,
    imageUrl: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=400',
    seasons: ['spring', 'summer'],
    occasions: ['casual', 'vacation'],
    favorite: false,
    wearCount: 15,
    lastWorn: subMonths(now, 3).toISOString(),
    condition: 'good',
    estimatedValue: 10,
  },
  {
    name: 'Wool Coat',
    category: 'outerwear',
    color: 'beige',
    brand: 'Max Mara',
    size: 'S',
    purchasePrice: 1200,
    imageUrl: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=400',
    seasons: ['winter'],
    occasions: ['work', 'formal', 'casual'],
    favorite: true,
    wearCount: 28,
    lastWorn: subDays(now, 10).toISOString(),
    condition: 'excellent',
    estimatedValue: 600,
  },
];

export function generateSampleItems(): ClothingItem[] {
  return sampleItems.map(item => ({
    ...item,
    id: uuidv4(),
    createdAt: subMonths(now, Math.floor(Math.random() * 12)).toISOString(),
  }));
}
